import { AgentConfig } from './types';

export function generateCopilotExtensionCode(agent: AgentConfig): string {
  const tools = agent.nodes.filter(n => n.type === 'tool');
  const prompts = agent.nodes.filter(n => n.type === 'prompt');
  const skills = agent.nodes.filter(n => n.type === 'skill');
  const instructions = agent.nodes.filter(n => n.type === 'instruction');
  const models = agent.nodes.filter(n => n.type === 'model');
  const guardrails = agent.nodes.filter(n => n.type === 'guardrail');

  const modelName = models.length > 0 ? (models[0].data.config.modelId as string || 'gpt-4o') : 'gpt-4o';

  const toolDefinitions = tools.map(t => `  {
    type: "function",
    function: {
      name: "${t.data.label.toLowerCase().replace(/\\s+/g, '_')}",
      description: "${t.data.description}",
      parameters: {
        type: "object",
        properties: ${JSON.stringify(t.data.config.parameters || {}, null, 8)},
      },
    },
  }`).join(',\n');

  const systemMessages = [
    agent.systemPrompt,
    ...prompts.map(p => p.data.config.content as string || p.data.description),
    ...instructions.map(i => i.data.config.content as string || i.data.description),
    ...skills.map(s => `You have the "${s.data.label}" skill: ${s.data.description}`),
    ...guardrails.map(g => `GUARDRAIL - ${g.data.label}: ${g.data.description}`),
  ].filter(Boolean);

  return `import { Octokit } from "@octokit/core";
import express from "express";
import { Readable } from "node:stream";

// =============================================================================
// ${agent.name}
// ${agent.description}
// Generated by Copilot Agent Builder
// =============================================================================

const app = express();

// Health check
app.get("/", (req, res) => {
  res.send("${agent.name} - GitHub Copilot Extension is running!");
});

// Tool definitions for function calling
const tools = [
${toolDefinitions}
];

// System messages
const systemMessages = ${JSON.stringify(systemMessages, null, 2)};

// Main handler
app.post("/", express.json(), async (req, res) => {
  const tokenForUser = req.get("X-GitHub-Token");
  const octokit = new Octokit({ auth: tokenForUser });
  const user = await octokit.request("GET /user");

  const payload = req.body;
  const messages = payload.messages;

  // Inject system messages
  systemMessages.forEach((msg) => {
    messages.unshift({ role: "system", content: msg });
  });

  messages.unshift({
    role: "system",
    content: \`The user's GitHub username is @\${user.data.login}\`,
  });

  // Call Copilot LLM with tools
  const copilotLLMResponse = await fetch(
    "https://api.githubcopilot.com/chat/completions",
    {
      method: "POST",
      headers: {
        authorization: \`Bearer \${tokenForUser}\`,
        "content-type": "application/json",
      },
      body: JSON.stringify({
        messages,
        model: "${modelName}",
        stream: true,
        ${tools.length > 0 ? 'tools,' : ''}
      }),
    }
  );

  Readable.from(copilotLLMResponse.body).pipe(res);
});

const port = Number(process.env.PORT || "3000");
app.listen(port, () => {
  console.log(\`${agent.name} running on port \${port}\`);
});
`;
}

export function generatePackageJson(agent: AgentConfig): string {
  return JSON.stringify({
    name: agent.name.toLowerCase().replace(/\\s+/g, '-'),
    private: true,
    description: agent.description,
    type: 'module',
    scripts: {
      start: 'node index.js',
      dev: 'node --watch index.js',
    },
    dependencies: {
      '@octokit/core': '^6.1.2',
      express: '^4.19.2',
    },
  }, null, 2);
}

export function generateReadme(agent: AgentConfig): string {
  const tools = agent.nodes.filter(n => n.type === 'tool');
  const skills = agent.nodes.filter(n => n.type === 'skill');

  return `# ${agent.name}

${agent.description}

## Features

${tools.map(t => `- **${t.data.label}**: ${t.data.description}`).join('\\n')}

## Skills

${skills.map(s => `- **${s.data.label}**: ${s.data.description}`).join('\\n')}

## Setup

1. Install dependencies: \`npm install\`
2. Start the server: \`npm start\`
3. Register as a GitHub Copilot Extension

## Generated by

Copilot Agent Builder - No-code drag-and-drop builder for GitHub Copilot SDK agents.
`;
}
