import { ToolboxItem } from './types';

export const toolboxItems: ToolboxItem[] = [
  // ============================================================
  // TOOLS (27 items)
  // ============================================================

  // --- File System ---
  {
    id: 'tool-read-file',
    name: 'Read File',
    category: 'tool',
    description: 'Read the contents of a file at a given path. Supports text files, JSON, YAML, and other common formats with optional encoding selection.',
    icon: 'FileText',
    color: '#06b6d4',
    config: { basePath: '/', encoding: 'utf-8' },
    tags: ['file-system', 'read', 'io'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-write-file',
    name: 'Write File',
    category: 'tool',
    description: 'Write content to a file at a specified path. Creates the file if it does not exist, or overwrites existing content. Supports atomic writes to prevent data corruption.',
    icon: 'FilePen',
    color: '#06b6d4',
    config: { basePath: '/', overwrite: true, createDirectories: true },
    tags: ['file-system', 'write', 'io'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-list-directory',
    name: 'List Directory',
    category: 'tool',
    description: 'List all files and directories within a given path. Supports recursive listing, glob pattern filtering, and options to include hidden files.',
    icon: 'FolderOpen',
    color: '#06b6d4',
    config: { basePath: '/', recursive: false, includeHidden: false, pattern: '*' },
    tags: ['file-system', 'directory', 'listing'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-search-files',
    name: 'Search Files',
    category: 'tool',
    description: 'Search for files matching a pattern or containing specific text content. Uses ripgrep-style regex for fast full-text search across entire project trees.',
    icon: 'SearchCode',
    color: '#06b6d4',
    config: { basePath: '/', regex: true, caseSensitive: false, maxResults: 100 },
    tags: ['file-system', 'search', 'grep'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-create-directory',
    name: 'Create Directory',
    category: 'tool',
    description: 'Create a new directory at the specified path. Supports creating nested directory structures recursively with configurable permissions.',
    icon: 'FolderPlus',
    color: '#06b6d4',
    config: { basePath: '/', recursive: true, permissions: '755' },
    tags: ['file-system', 'directory', 'create'],
    source: 'copilot-extensions-sdk',
  },

  // --- Terminal ---
  {
    id: 'tool-execute-command',
    name: 'Execute Command',
    category: 'tool',
    description: 'Execute a shell command in the workspace terminal. Captures stdout, stderr, and exit code. Supports timeout configuration and working directory selection.',
    icon: 'Terminal',
    color: '#06b6d4',
    config: { shell: '/bin/bash', timeout: 30000, cwd: '.' },
    tags: ['terminal', 'shell', 'command'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-run-script',
    name: 'Run Script',
    category: 'tool',
    description: 'Execute a project script defined in package.json, Makefile, or other task runners. Automatically detects the project type and uses the appropriate runner.',
    icon: 'Play',
    color: '#06b6d4',
    config: { runner: 'auto', env: {} },
    tags: ['terminal', 'script', 'task-runner'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-install-packages',
    name: 'Install Packages',
    category: 'tool',
    description: 'Install project dependencies using the detected package manager (npm, yarn, pnpm, pip, cargo, etc.). Supports installing specific packages or restoring from lockfile.',
    icon: 'PackagePlus',
    color: '#06b6d4',
    config: { packageManager: 'auto', saveDev: false },
    tags: ['terminal', 'packages', 'dependencies'],
    source: 'copilot-extensions-sdk',
  },

  // --- Git ---
  {
    id: 'tool-git-commit',
    name: 'Git Commit',
    category: 'tool',
    description: 'Stage and commit changes to the local Git repository. Supports conventional commit format, co-author attribution, and GPG signing.',
    icon: 'GitCommitHorizontal',
    color: '#06b6d4',
    config: { conventionalCommit: true, signoff: false, allowEmpty: false },
    tags: ['git', 'version-control', 'commit'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-git-push',
    name: 'Git Push',
    category: 'tool',
    description: 'Push local commits to the remote repository. Supports setting upstream tracking branches, force push with lease, and tag pushing.',
    icon: 'GitPullRequestArrow',
    color: '#06b6d4',
    config: { remote: 'origin', setUpstream: true, forceLease: false },
    tags: ['git', 'version-control', 'push'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-git-pull',
    name: 'Git Pull',
    category: 'tool',
    description: 'Pull the latest changes from the remote repository and merge them into the current branch. Supports rebase mode and auto-stash for clean working trees.',
    icon: 'GitPullRequest',
    color: '#06b6d4',
    config: { remote: 'origin', rebase: false, autoStash: true },
    tags: ['git', 'version-control', 'pull'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-git-branch',
    name: 'Git Branch',
    category: 'tool',
    description: 'Create, list, rename, or delete Git branches. Supports checking out new branches, listing remote branches, and branch comparison.',
    icon: 'GitBranch',
    color: '#06b6d4',
    config: { action: 'create', checkout: true },
    tags: ['git', 'version-control', 'branch'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-git-diff',
    name: 'Git Diff',
    category: 'tool',
    description: 'Show the differences between commits, branches, or the working tree. Supports staged vs unstaged diffs, stat-only output, and file-specific filtering.',
    icon: 'GitCompareArrows',
    color: '#06b6d4',
    config: { staged: false, stat: false, nameOnly: false },
    tags: ['git', 'version-control', 'diff'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-git-status',
    name: 'Git Status',
    category: 'tool',
    description: 'Display the current state of the working directory and staging area. Shows tracked, untracked, modified, and staged files with branch information.',
    icon: 'GitFork',
    color: '#06b6d4',
    config: { short: false, showBranch: true },
    tags: ['git', 'version-control', 'status'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-git-log',
    name: 'Git Log',
    category: 'tool',
    description: 'Show the commit history for the current branch. Supports oneline format, graph output, date filtering, and author filtering.',
    icon: 'History',
    color: '#06b6d4',
    config: { maxCount: 20, oneline: true, graph: false },
    tags: ['git', 'version-control', 'log', 'history'],
    source: 'copilot-extensions-sdk',
  },

  // --- GitHub API ---
  {
    id: 'tool-github-create-issue',
    name: 'Create Issue',
    category: 'tool',
    description: 'Create a new issue in a GitHub repository with a title, body, labels, assignees, and milestone. Supports markdown formatting in the issue body.',
    icon: 'CircleDot',
    color: '#06b6d4',
    config: { owner: '', repo: '', labels: [], assignees: [] },
    tags: ['github', 'issues', 'api'],
    source: 'copilot-github-models-extension',
  },
  {
    id: 'tool-github-create-pr',
    name: 'Create Pull Request',
    category: 'tool',
    description: 'Open a pull request from the current branch to a target branch. Auto-generates a description from the commit history and supports draft PRs and reviewers.',
    icon: 'GitPullRequestCreate',
    color: '#06b6d4',
    config: { base: 'main', draft: false, reviewers: [] },
    tags: ['github', 'pull-request', 'api'],
    source: 'copilot-github-models-extension',
  },
  {
    id: 'tool-github-list-repos',
    name: 'List Repositories',
    category: 'tool',
    description: 'List repositories for a user or organization on GitHub. Supports filtering by visibility, language, sort order, and pagination.',
    icon: 'Library',
    color: '#06b6d4',
    config: { visibility: 'all', sort: 'updated', perPage: 30 },
    tags: ['github', 'repositories', 'api'],
    source: 'copilot-github-models-extension',
  },
  {
    id: 'tool-github-review-pr',
    name: 'Review Pull Request',
    category: 'tool',
    description: 'Submit a review on a GitHub pull request with comments, approval, or requested changes. Supports inline code comments and review summaries.',
    icon: 'MessageSquareCode',
    color: '#06b6d4',
    config: { event: 'COMMENT', includeLineComments: true },
    tags: ['github', 'pull-request', 'review', 'api'],
    source: 'copilot-github-models-extension',
  },
  {
    id: 'tool-github-merge-pr',
    name: 'Merge Pull Request',
    category: 'tool',
    description: 'Merge an approved pull request using the specified merge strategy. Supports merge commits, squash merges, and rebase merges with optional commit message customization.',
    icon: 'GitMerge',
    color: '#06b6d4',
    config: { mergeMethod: 'squash', deleteBranch: true },
    tags: ['github', 'pull-request', 'merge', 'api'],
    source: 'copilot-github-models-extension',
  },

  // --- Code Analysis ---
  {
    id: 'tool-lint-code',
    name: 'Lint Code',
    category: 'tool',
    description: 'Run linting analysis on source files to detect code style issues, potential bugs, and anti-patterns. Supports ESLint, Pylint, RuboCop, and other popular linters.',
    icon: 'ScanSearch',
    color: '#06b6d4',
    config: { linter: 'auto', fix: false, configPath: '' },
    tags: ['code-analysis', 'lint', 'quality'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-format-code',
    name: 'Format Code',
    category: 'tool',
    description: 'Automatically format source code according to configured style rules. Supports Prettier, Black, gofmt, rustfmt, and other formatters with project-level configuration.',
    icon: 'Paintbrush',
    color: '#06b6d4',
    config: { formatter: 'auto', configPath: '', writeInPlace: true },
    tags: ['code-analysis', 'format', 'style'],
    source: 'copilot-extensions-sdk',
  },

  // --- Web/API ---
  {
    id: 'tool-http-request',
    name: 'HTTP Request',
    category: 'tool',
    description: 'Send an HTTP request to any URL with configurable method, headers, body, and authentication. Supports GET, POST, PUT, PATCH, DELETE, and custom methods.',
    icon: 'Globe',
    color: '#06b6d4',
    config: { method: 'GET', headers: {}, timeout: 10000, followRedirects: true },
    tags: ['web', 'api', 'http', 'network'],
    source: 'copilot-extensions-sdk',
  },
  {
    id: 'tool-fetch-url',
    name: 'Fetch URL',
    category: 'tool',
    description: 'Fetch and parse content from a web URL. Converts HTML to readable text, extracts metadata, and supports JSON and XML response parsing.',
    icon: 'Link',
    color: '#06b6d4',
    config: { parseHtml: true, extractMetadata: true, timeout: 15000 },
    tags: ['web', 'fetch', 'scrape'],
    source: 'copilot-extensions-sdk',
  },

  // --- Database ---
  {
    id: 'tool-db-query',
    name: 'Database Query',
    category: 'tool',
    description: 'Execute a read-only SQL query against a connected database and return the results. Supports parameterized queries to prevent SQL injection.',
    icon: 'Database',
    color: '#06b6d4',
    config: { connectionString: '', readOnly: true, timeout: 5000, maxRows: 1000 },
    tags: ['database', 'sql', 'query'],
  },
  {
    id: 'tool-db-schema',
    name: 'Database Schema',
    category: 'tool',
    description: 'Inspect the database schema including tables, columns, indexes, foreign keys, and constraints. Useful for understanding data models and generating migrations.',
    icon: 'TableProperties',
    color: '#06b6d4',
    config: { connectionString: '', includeIndexes: true, includeConstraints: true },
    tags: ['database', 'schema', 'inspection'],
  },

  // --- Testing ---
  {
    id: 'tool-run-tests',
    name: 'Run Tests',
    category: 'tool',
    description: 'Execute the project test suite using the detected test framework (Jest, Pytest, Mocha, RSpec, etc.). Supports running specific test files, watch mode, and verbose output.',
    icon: 'FlaskConical',
    color: '#06b6d4',
    config: { framework: 'auto', watch: false, verbose: true, coverage: false },
    tags: ['testing', 'test-runner', 'quality'],
    source: 'copilot-extensions-sdk',
  },

  // ============================================================
  // PROMPTS (16 items)
  // ============================================================
  {
    id: 'prompt-code-review',
    name: 'Code Review',
    category: 'prompt',
    description: 'Perform a thorough code review focusing on correctness, readability, performance, security, and adherence to best practices. Provide actionable feedback with specific suggestions.',
    icon: 'Eye',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are an expert code reviewer. Analyze the provided code for bugs, security vulnerabilities, performance issues, and style violations. Provide specific, actionable feedback.',
      temperature: 0.3,
      focus: ['correctness', 'security', 'performance', 'readability'],
    },
    tags: ['review', 'quality', 'best-practices'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-bug-fix',
    name: 'Bug Fix',
    category: 'prompt',
    description: 'Analyze code to identify and fix bugs. Provides root cause analysis, step-by-step debugging guidance, and a corrected implementation with explanations.',
    icon: 'Bug',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are an expert debugger. Analyze the provided code to find the root cause of bugs. Explain the issue clearly and provide a corrected implementation with reasoning.',
      temperature: 0.2,
      includeTests: true,
    },
    tags: ['debugging', 'fix', 'troubleshooting'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-refactor',
    name: 'Refactor Code',
    category: 'prompt',
    description: 'Refactor code to improve its internal structure without changing external behavior. Applies SOLID principles, design patterns, and clean code practices.',
    icon: 'RefreshCw',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are a refactoring expert. Improve the internal structure of the provided code while preserving its external behavior. Apply SOLID principles and clean code practices.',
      temperature: 0.3,
      preserveApi: true,
    },
    tags: ['refactoring', 'clean-code', 'design-patterns'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-documentation',
    name: 'Generate Documentation',
    category: 'prompt',
    description: 'Generate comprehensive documentation including JSDoc/docstring comments, README sections, API reference tables, and usage examples from source code.',
    icon: 'BookOpen',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are a technical writer. Generate clear, comprehensive documentation for the provided code. Include parameter descriptions, return types, usage examples, and edge cases.',
      temperature: 0.4,
      format: 'markdown',
      includeExamples: true,
    },
    tags: ['documentation', 'docs', 'technical-writing'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-test-generation',
    name: 'Generate Tests',
    category: 'prompt',
    description: 'Generate comprehensive unit and integration tests for the provided code. Covers happy paths, edge cases, error scenarios, and boundary conditions.',
    icon: 'TestTubeDiagonal',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are a testing expert. Generate comprehensive tests for the provided code covering happy paths, edge cases, error handling, and boundary conditions. Use the appropriate testing framework.',
      temperature: 0.3,
      framework: 'auto',
      coverageTarget: 90,
    },
    tags: ['testing', 'unit-tests', 'test-generation'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-security-audit',
    name: 'Security Audit',
    category: 'prompt',
    description: 'Perform a security audit of the code identifying vulnerabilities such as injection attacks, XSS, CSRF, insecure dependencies, and data exposure risks.',
    icon: 'ShieldAlert',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are a security expert. Audit the provided code for vulnerabilities including injection attacks, XSS, CSRF, insecure data handling, and dependency risks. Rate severity and provide remediation steps.',
      temperature: 0.2,
      severityLevels: ['critical', 'high', 'medium', 'low'],
    },
    tags: ['security', 'audit', 'vulnerability'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-performance-optimization',
    name: 'Performance Optimization',
    category: 'prompt',
    description: 'Analyze code for performance bottlenecks and suggest optimizations. Covers algorithmic complexity, memory usage, caching strategies, and database query optimization.',
    icon: 'Gauge',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are a performance engineer. Analyze the provided code for bottlenecks, inefficient algorithms, memory leaks, and slow operations. Suggest concrete optimizations with benchmarks.',
      temperature: 0.3,
      focus: ['time-complexity', 'memory', 'io', 'caching'],
    },
    tags: ['performance', 'optimization', 'profiling'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-architecture-design',
    name: 'Architecture Design',
    category: 'prompt',
    description: 'Design system architecture including component breakdown, data flow diagrams, API contracts, and technology selection with trade-off analysis.',
    icon: 'Blocks',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are a software architect. Design a scalable, maintainable architecture for the described system. Include component diagrams, data flow, API contracts, and technology recommendations with trade-off analysis.',
      temperature: 0.5,
      includeTradeoffs: true,
    },
    tags: ['architecture', 'design', 'system-design'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-api-design',
    name: 'API Design',
    category: 'prompt',
    description: 'Design RESTful or GraphQL APIs with endpoint definitions, request/response schemas, authentication flows, pagination strategies, and versioning approaches.',
    icon: 'Webhook',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are an API design expert. Design a clean, consistent API following REST or GraphQL best practices. Include endpoint definitions, schemas, authentication, pagination, and error handling.',
      temperature: 0.4,
      style: 'REST',
      includeOpenApi: true,
    },
    tags: ['api', 'design', 'rest', 'graphql'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-database-design',
    name: 'Database Design',
    category: 'prompt',
    description: 'Design database schemas with entity-relationship modeling, normalization, indexing strategies, migration scripts, and query optimization guidance.',
    icon: 'DatabaseZap',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are a database architect. Design an efficient database schema with proper normalization, indexing, constraints, and relationships. Include migration scripts and query optimization tips.',
      temperature: 0.3,
      dbType: 'postgresql',
      includeERD: true,
    },
    tags: ['database', 'schema-design', 'modeling'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-pirate-mode',
    name: 'Pirate Mode',
    category: 'prompt',
    description: 'Arrr! Respond to all queries in the style of a swashbuckling pirate. Technical accuracy be maintained, but delivery be in full pirate vernacular, matey!',
    icon: 'Skull',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are a pirate programmer named Blackbeard. Respond to all queries in pirate speak while maintaining technical accuracy. Use nautical metaphors for programming concepts. Arrr!',
      temperature: 0.8,
      personality: 'pirate',
    },
    tags: ['fun', 'personality', 'pirate'],
    source: 'copilot-blackbeard-extension',
  },
  {
    id: 'prompt-explain-code',
    name: 'Explain Code',
    category: 'prompt',
    description: 'Explain code in clear, plain language suitable for the specified audience level. Breaks down complex logic, identifies patterns, and explains the purpose of each section.',
    icon: 'MessageCircleQuestion',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are a patient, expert teacher. Explain the provided code in clear, plain language. Break down complex logic step by step, identify design patterns, and explain the purpose of key sections.',
      temperature: 0.4,
      audienceLevel: 'intermediate',
    },
    tags: ['explanation', 'learning', 'teaching'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-code-translation',
    name: 'Code Translation',
    category: 'prompt',
    description: 'Translate code from one programming language to another while preserving logic, performance characteristics, and idiomatic patterns of the target language.',
    icon: 'ArrowLeftRight',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are a polyglot programmer. Translate the provided code to the target language while preserving logic and using idiomatic patterns. Highlight any language-specific differences or limitations.',
      temperature: 0.3,
      sourceLanguage: 'auto',
      targetLanguage: '',
    },
    tags: ['translation', 'language', 'migration'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-accessibility-review',
    name: 'Accessibility Review',
    category: 'prompt',
    description: 'Review UI code for accessibility compliance with WCAG 2.1 guidelines. Checks for proper ARIA labels, keyboard navigation, color contrast, screen reader support, and semantic HTML.',
    icon: 'Accessibility',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are an accessibility expert. Review the provided code for WCAG 2.1 compliance. Check ARIA labels, keyboard navigation, color contrast, semantic HTML, and screen reader support. Provide specific fixes.',
      temperature: 0.3,
      standard: 'WCAG 2.1 AA',
    },
    tags: ['accessibility', 'a11y', 'wcag', 'ui'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-migration-guide',
    name: 'Migration Guide',
    category: 'prompt',
    description: 'Generate a step-by-step migration guide for upgrading frameworks, libraries, or languages. Includes breaking changes, deprecation notices, and code transformation examples.',
    icon: 'Route',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are a migration specialist. Create a detailed migration guide covering breaking changes, deprecations, and step-by-step code transformations. Include rollback strategies and testing checkpoints.',
      temperature: 0.4,
      includeRollback: true,
    },
    tags: ['migration', 'upgrade', 'guide'],
    source: 'copilot-docs',
  },
  {
    id: 'prompt-commit-message',
    name: 'Commit Message',
    category: 'prompt',
    description: 'Generate a clear, conventional commit message from a diff or set of changes. Follows the Conventional Commits specification with scope, type, and detailed description.',
    icon: 'MessageSquare',
    color: '#f472b6',
    config: {
      systemPrompt: 'You are a commit message expert. Analyze the provided diff and generate a clear, conventional commit message. Use the format: type(scope): description. Include a detailed body when the changes are complex.',
      temperature: 0.3,
      convention: 'conventional-commits',
    },
    tags: ['git', 'commit', 'message'],
    source: 'copilot-docs',
  },

  // ============================================================
  // SKILLS (21 items)
  // ============================================================
  {
    id: 'skill-github-automation',
    name: 'GitHub Automation',
    category: 'skill',
    description: 'Automate GitHub workflows including issue triage, PR labeling, release drafting, changelog generation, and repository maintenance using the GitHub API.',
    icon: 'Github',
    color: '#34d399',
    config: { owner: '', repo: '', authToken: '', workflows: [] },
    tags: ['github', 'automation', 'devops'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-slack-integration',
    name: 'Slack Integration',
    category: 'skill',
    description: 'Integrate with Slack to send notifications, manage channels, post formatted messages, and respond to slash commands. Supports Block Kit for rich message layouts.',
    icon: 'MessageSquareShare',
    color: '#34d399',
    config: { webhookUrl: '', channel: '', botToken: '' },
    tags: ['slack', 'messaging', 'notifications'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-jira-integration',
    name: 'Jira Integration',
    category: 'skill',
    description: 'Manage Jira issues, sprints, and boards. Create and update tickets, transition issue statuses, log work, and sync development progress with project tracking.',
    icon: 'KanbanSquare',
    color: '#34d399',
    config: { baseUrl: '', projectKey: '', apiToken: '' },
    tags: ['jira', 'project-management', 'agile'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-aws-deployment',
    name: 'AWS Deployment',
    category: 'skill',
    description: 'Deploy applications to AWS using services like EC2, ECS, Lambda, S3, CloudFront, and RDS. Manages infrastructure as code with CloudFormation or CDK templates.',
    icon: 'Cloud',
    color: '#34d399',
    config: { region: 'us-east-1', profile: 'default', service: 'lambda' },
    tags: ['aws', 'cloud', 'deployment', 'infrastructure'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-docker-management',
    name: 'Docker Management',
    category: 'skill',
    description: 'Build, run, and manage Docker containers and images. Supports multi-stage builds, docker-compose orchestration, image optimization, and container health monitoring.',
    icon: 'Container',
    color: '#34d399',
    config: { dockerHost: 'unix:///var/run/docker.sock', composeFile: 'docker-compose.yml' },
    tags: ['docker', 'containers', 'devops'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-kubernetes-ops',
    name: 'Kubernetes Operations',
    category: 'skill',
    description: 'Manage Kubernetes clusters, deployments, services, and pods. Supports rolling updates, auto-scaling, config maps, secrets management, and cluster monitoring.',
    icon: 'Network',
    color: '#34d399',
    config: { context: '', namespace: 'default', kubeconfig: '' },
    tags: ['kubernetes', 'k8s', 'orchestration', 'devops'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-firebase-admin',
    name: 'Firebase Administration',
    category: 'skill',
    description: 'Manage Firebase projects including Firestore databases, Authentication rules, Cloud Functions, Storage buckets, and Hosting deployments.',
    icon: 'Flame',
    color: '#34d399',
    config: { projectId: '', serviceAccountPath: '' },
    tags: ['firebase', 'google-cloud', 'backend'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-stripe-payments',
    name: 'Stripe Payment Processing',
    category: 'skill',
    description: 'Integrate Stripe for payment processing including checkout sessions, subscriptions, invoices, refunds, and webhook event handling with PCI-compliant patterns.',
    icon: 'CreditCard',
    color: '#34d399',
    config: { apiKey: '', webhookSecret: '', currency: 'usd' },
    tags: ['stripe', 'payments', 'billing', 'e-commerce'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-postgresql-management',
    name: 'PostgreSQL Management',
    category: 'skill',
    description: 'Manage PostgreSQL databases including schema design, migrations, query optimization, backup/restore operations, replication setup, and performance tuning.',
    icon: 'Database',
    color: '#34d399',
    config: { host: 'localhost', port: 5432, database: '', sslMode: 'prefer' },
    tags: ['postgresql', 'database', 'sql'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-mongodb-ops',
    name: 'MongoDB Operations',
    category: 'skill',
    description: 'Manage MongoDB databases with collection management, aggregation pipelines, index optimization, sharding configuration, and replica set administration.',
    icon: 'Leaf',
    color: '#34d399',
    config: { connectionUri: '', database: '', authSource: 'admin' },
    tags: ['mongodb', 'nosql', 'database'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-email-automation',
    name: 'Email Automation',
    category: 'skill',
    description: 'Automate email workflows using providers like SendGrid, SES, or Mailgun. Supports templated emails, bulk sending, delivery tracking, and bounce handling.',
    icon: 'Mail',
    color: '#34d399',
    config: { provider: 'sendgrid', apiKey: '', fromAddress: '' },
    tags: ['email', 'automation', 'notifications'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-pdf-processing',
    name: 'PDF Processing',
    category: 'skill',
    description: 'Generate, parse, merge, split, and transform PDF documents. Supports text extraction, form filling, digital signatures, watermarking, and OCR integration.',
    icon: 'FileDown',
    color: '#34d399',
    config: { outputFormat: 'pdf', quality: 'high', ocr: false },
    tags: ['pdf', 'document', 'processing'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-image-processing',
    name: 'Image Processing',
    category: 'skill',
    description: 'Process images with resizing, cropping, format conversion, compression, watermarking, and metadata extraction. Supports batch operations and optimization for web.',
    icon: 'Image',
    color: '#34d399',
    config: { maxWidth: 1920, quality: 85, format: 'webp' },
    tags: ['image', 'media', 'processing'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-data-pipeline',
    name: 'Data Pipeline',
    category: 'skill',
    description: 'Build and manage ETL/ELT data pipelines for extracting, transforming, and loading data between systems. Supports scheduling, error handling, and data validation.',
    icon: 'Workflow',
    color: '#34d399',
    config: { scheduler: 'cron', retryPolicy: { maxRetries: 3, backoff: 'exponential' } },
    tags: ['data', 'etl', 'pipeline', 'analytics'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-cicd-pipeline',
    name: 'CI/CD Pipeline',
    category: 'skill',
    description: 'Configure and manage CI/CD pipelines using GitHub Actions, GitLab CI, CircleCI, or Jenkins. Automate build, test, lint, and deploy stages with environment promotion.',
    icon: 'Rocket',
    color: '#34d399',
    config: { provider: 'github-actions', stages: ['build', 'test', 'deploy'], autoMerge: false },
    tags: ['ci-cd', 'automation', 'devops', 'deployment'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-code-generation',
    name: 'Code Generation',
    category: 'skill',
    description: 'Generate boilerplate code, scaffolding, and project templates from specifications. Supports CRUD endpoints, model definitions, form components, and API clients.',
    icon: 'Wand2',
    color: '#34d399',
    config: { language: 'typescript', framework: 'auto', style: 'functional' },
    tags: ['codegen', 'scaffolding', 'templates'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-api-integration',
    name: 'API Integration',
    category: 'skill',
    description: 'Connect and integrate with third-party APIs including authentication setup, request/response mapping, rate limit handling, and error recovery patterns.',
    icon: 'Plug',
    color: '#34d399',
    config: { authType: 'bearer', retryOn: [429, 500, 502, 503], timeout: 30000 },
    tags: ['api', 'integration', 'third-party'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-webhook-management',
    name: 'Webhook Management',
    category: 'skill',
    description: 'Set up and manage webhook endpoints for receiving real-time events. Includes signature verification, payload parsing, retry logic, and event routing.',
    icon: 'Anchor',
    color: '#34d399',
    config: { secret: '', verifySignature: true, retryCount: 3 },
    tags: ['webhooks', 'events', 'real-time'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-mcp-server-builder',
    name: 'MCP Server Builder',
    category: 'skill',
    description: 'Build Model Context Protocol servers that expose tools, resources, and prompts to AI agents. Supports stdio and HTTP transports with automatic schema generation.',
    icon: 'Server',
    color: '#34d399',
    config: { transport: 'stdio', name: '', version: '1.0.0' },
    tags: ['mcp', 'server', 'ai-tools', 'protocol'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-fullstack-dev',
    name: 'Full Stack Development',
    category: 'skill',
    description: 'End-to-end full stack development combining frontend frameworks (React, Next.js, Vue) with backend services (Node.js, Python, Go), databases, and deployment.',
    icon: 'Layers',
    color: '#34d399',
    config: { frontend: 'react', backend: 'node', database: 'postgresql', deployment: 'vercel' },
    tags: ['fullstack', 'frontend', 'backend', 'development'],
    source: 'awesome-claude-skills',
  },
  {
    id: 'skill-frontend-builder',
    name: 'Frontend Builder',
    category: 'skill',
    description: 'Build responsive, accessible frontend interfaces using modern frameworks. Generates component hierarchies, state management, routing, and styling from design specs.',
    icon: 'Layout',
    color: '#34d399',
    config: { framework: 'react', styling: 'tailwind', stateManagement: 'zustand' },
    tags: ['frontend', 'ui', 'components', 'development'],
    source: 'awesome-claude-skills',
  },

  // ============================================================
  // INSTRUCTIONS (12 items)
  // ============================================================
  {
    id: 'instruction-response-format',
    name: 'Response Format',
    category: 'instruction',
    description: 'Control the output format of agent responses. Choose between structured markdown with headings, raw JSON for programmatic consumption, or plain text for simplicity.',
    icon: 'FileJson',
    color: '#fbbf24',
    config: { format: 'markdown', includeCodeBlocks: true, maxLength: 0 },
    tags: ['format', 'output', 'response'],
  },
  {
    id: 'instruction-verbosity-level',
    name: 'Verbosity Level',
    category: 'instruction',
    description: 'Set the detail level of agent responses. Concise mode gives brief answers, standard provides balanced detail, and verbose includes comprehensive explanations and examples.',
    icon: 'SlidersHorizontal',
    color: '#fbbf24',
    config: { level: 'standard', options: ['concise', 'standard', 'verbose'] },
    tags: ['verbosity', 'detail', 'output'],
  },
  {
    id: 'instruction-language-style',
    name: 'Language Style',
    category: 'instruction',
    description: 'Configure the tone and language style of responses. Options include professional, casual, academic, and technical modes with adjustable formality levels.',
    icon: 'Languages',
    color: '#fbbf24',
    config: { style: 'professional', formality: 'medium', useJargon: true },
    tags: ['tone', 'language', 'style'],
  },
  {
    id: 'instruction-error-handling',
    name: 'Error Handling Strategy',
    category: 'instruction',
    description: 'Define how the agent handles errors during tool execution. Options include fail-fast, retry with backoff, graceful degradation, and user-prompt-on-error strategies.',
    icon: 'ShieldCheck',
    color: '#fbbf24',
    config: { strategy: 'retry', maxRetries: 3, backoff: 'exponential', fallback: 'notify-user' },
    tags: ['error-handling', 'resilience', 'strategy'],
  },
  {
    id: 'instruction-code-style-guide',
    name: 'Code Style Guide',
    category: 'instruction',
    description: 'Enforce a specific code style guide for all generated code. Supports PEP 8 for Python, Airbnb/Standard for JavaScript, Google style guides, and custom rulesets.',
    icon: 'Ruler',
    color: '#fbbf24',
    config: { guide: 'airbnb', language: 'typescript', indentation: 'spaces', indentSize: 2, semicolons: true },
    tags: ['code-style', 'linting', 'conventions'],
  },
  {
    id: 'instruction-security-first',
    name: 'Security First',
    category: 'instruction',
    description: 'Instruct the agent to prioritize security in all generated code. Includes input validation, output encoding, parameterized queries, HTTPS enforcement, and secret management.',
    icon: 'Lock',
    color: '#fbbf24',
    config: { enforceHttps: true, sanitizeInput: true, parameterizedQueries: true, noHardcodedSecrets: true },
    tags: ['security', 'best-practices', 'hardening'],
  },
  {
    id: 'instruction-tdd-approach',
    name: 'TDD Approach',
    category: 'instruction',
    description: 'Follow Test-Driven Development methodology. The agent writes failing tests first, then implements the minimum code to pass, then refactors while maintaining green tests.',
    icon: 'TestTube',
    color: '#fbbf24',
    config: { writeTestsFirst: true, minCoverage: 80, framework: 'auto', redGreenRefactor: true },
    tags: ['tdd', 'testing', 'methodology'],
  },
  {
    id: 'instruction-agile-methodology',
    name: 'Agile Methodology',
    category: 'instruction',
    description: 'Structure work following Agile principles with user stories, acceptance criteria, sprint planning, and iterative delivery. Break features into small, shippable increments.',
    icon: 'Repeat',
    color: '#fbbf24',
    config: { sprintDuration: '2 weeks', storyFormat: 'As a... I want... So that...', estimationUnit: 'story-points' },
    tags: ['agile', 'methodology', 'planning'],
  },
  {
    id: 'instruction-documentation-standard',
    name: 'Documentation Standard',
    category: 'instruction',
    description: 'Require documentation for all code changes. Enforces JSDoc/docstrings, README updates, changelog entries, and inline comments for complex logic.',
    icon: 'BookMarked',
    color: '#fbbf24',
    config: { requireDocstrings: true, updateReadme: true, changelogFormat: 'keep-a-changelog', inlineComments: 'complex-only' },
    tags: ['documentation', 'standards', 'comments'],
  },
  {
    id: 'instruction-performance-budget',
    name: 'Performance Budget',
    category: 'instruction',
    description: 'Set performance budgets for generated code and applications. Defines limits for bundle size, load time, time-to-interactive, and API response latency.',
    icon: 'Timer',
    color: '#fbbf24',
    config: { maxBundleSize: '250kb', maxLoadTime: '3s', maxApiLatency: '200ms', maxMemoryUsage: '512mb' },
    tags: ['performance', 'budget', 'optimization'],
  },
  {
    id: 'instruction-accessibility-standards',
    name: 'Accessibility Standards',
    category: 'instruction',
    description: 'Enforce accessibility standards in all generated UI code. Requires ARIA attributes, keyboard navigation, sufficient color contrast, and screen reader compatibility.',
    icon: 'HeartHandshake',
    color: '#fbbf24',
    config: { standard: 'WCAG 2.1 AA', requireAriaLabels: true, minContrastRatio: 4.5, keyboardNavigation: true },
    tags: ['accessibility', 'a11y', 'wcag', 'standards'],
  },
  {
    id: 'instruction-dry-principle',
    name: 'DRY Principle',
    category: 'instruction',
    description: 'Enforce the Don\'t Repeat Yourself principle. The agent extracts repeated code into reusable functions, components, or modules and avoids code duplication.',
    icon: 'Copy',
    color: '#fbbf24',
    config: { maxDuplication: 2, extractFunctions: true, extractComponents: true, suggestAbstractions: true },
    tags: ['dry', 'clean-code', 'reusability'],
  },

  // ============================================================
  // MODELS (8 items)
  // ============================================================
  {
    id: 'model-gpt-4o',
    name: 'GPT-4o',
    category: 'model',
    description: 'OpenAI\'s most capable multimodal model. Excels at complex reasoning, code generation, creative writing, and vision tasks with fast response times and broad knowledge.',
    icon: 'Sparkles',
    color: '#818cf8',
    config: { provider: 'openai', modelId: 'gpt-4o', maxTokens: 4096, temperature: 0.7, supportsVision: true },
    tags: ['openai', 'gpt-4', 'multimodal', 'flagship'],
  },
  {
    id: 'model-gpt-4o-mini',
    name: 'GPT-4o Mini',
    category: 'model',
    description: 'A smaller, faster, and more cost-effective variant of GPT-4o. Ideal for simpler tasks, high-volume processing, and applications where latency and cost are priorities.',
    icon: 'Zap',
    color: '#818cf8',
    config: { provider: 'openai', modelId: 'gpt-4o-mini', maxTokens: 4096, temperature: 0.7, supportsVision: true },
    tags: ['openai', 'gpt-4', 'fast', 'cost-effective'],
  },
  {
    id: 'model-claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    category: 'model',
    description: 'Anthropic\'s balanced model offering strong reasoning, coding, and analysis capabilities with a large context window. Excellent for code generation and technical tasks.',
    icon: 'Brain',
    color: '#818cf8',
    config: { provider: 'anthropic', modelId: 'claude-3-5-sonnet-20241022', maxTokens: 8192, temperature: 0.7, supportsVision: true },
    tags: ['anthropic', 'claude', 'balanced', 'coding'],
  },
  {
    id: 'model-claude-3-opus',
    name: 'Claude 3 Opus',
    category: 'model',
    description: 'Anthropic\'s most powerful model for complex analysis, nuanced reasoning, and long-form content. Provides the highest quality responses for demanding intellectual tasks.',
    icon: 'Crown',
    color: '#818cf8',
    config: { provider: 'anthropic', modelId: 'claude-3-opus-20240229', maxTokens: 4096, temperature: 0.7, supportsVision: true },
    tags: ['anthropic', 'claude', 'powerful', 'reasoning'],
  },
  {
    id: 'model-gemini-pro',
    name: 'Gemini Pro',
    category: 'model',
    description: 'Google DeepMind\'s advanced multimodal model with strong reasoning and coding abilities. Features native tool use, large context windows, and Google Search grounding.',
    icon: 'Diamond',
    color: '#818cf8',
    config: { provider: 'google', modelId: 'gemini-pro', maxTokens: 8192, temperature: 0.7, supportsVision: true },
    tags: ['google', 'gemini', 'multimodal'],
  },
  {
    id: 'model-llama-3',
    name: 'Llama 3',
    category: 'model',
    description: 'Meta\'s open-source large language model offering competitive performance with full transparency. Can be self-hosted for data privacy and custom fine-tuning.',
    icon: 'CircuitBoard',
    color: '#818cf8',
    config: { provider: 'meta', modelId: 'llama-3-70b', maxTokens: 4096, temperature: 0.7, openSource: true },
    tags: ['meta', 'llama', 'open-source', 'self-hosted'],
  },
  {
    id: 'model-mistral-large',
    name: 'Mistral Large',
    category: 'model',
    description: 'Mistral AI\'s flagship model with strong multilingual capabilities and code understanding. Offers a good balance of performance and efficiency for enterprise use.',
    icon: 'Wind',
    color: '#818cf8',
    config: { provider: 'mistral', modelId: 'mistral-large-latest', maxTokens: 4096, temperature: 0.7 },
    tags: ['mistral', 'multilingual', 'enterprise'],
  },
  {
    id: 'model-codestral',
    name: 'Codestral',
    category: 'model',
    description: 'Mistral AI\'s specialized code generation model optimized for programming tasks. Supports over 80 languages with fill-in-the-middle and instruction-following capabilities.',
    icon: 'Code',
    color: '#818cf8',
    config: { provider: 'mistral', modelId: 'codestral-latest', maxTokens: 4096, temperature: 0.3, specialization: 'code' },
    tags: ['mistral', 'code', 'specialized'],
  },

  // ============================================================
  // GUARDRAILS (8 items)
  // ============================================================
  {
    id: 'guardrail-content-filter',
    name: 'Content Filter',
    category: 'guardrail',
    description: 'Filter agent outputs for harmful, inappropriate, or off-topic content. Blocks responses containing hate speech, personal information, or policy-violating material.',
    icon: 'Filter',
    color: '#ef4444',
    config: { filterLevel: 'strict', categories: ['hate', 'violence', 'pii', 'profanity'], action: 'block' },
    tags: ['safety', 'content-moderation', 'filtering'],
  },
  {
    id: 'guardrail-rate-limiter',
    name: 'Rate Limiter',
    category: 'guardrail',
    description: 'Limit the rate of agent actions to prevent excessive API calls, runaway loops, or resource exhaustion. Configurable with sliding window, token bucket, or fixed window algorithms.',
    icon: 'Hourglass',
    color: '#ef4444',
    config: { maxRequests: 60, windowSeconds: 60, algorithm: 'sliding-window', burstLimit: 10 },
    tags: ['rate-limiting', 'throttling', 'protection'],
  },
  {
    id: 'guardrail-input-validator',
    name: 'Input Validator',
    category: 'guardrail',
    description: 'Validate and sanitize all inputs before they reach the agent. Checks for prompt injection attempts, malformed data, oversized payloads, and forbidden patterns.',
    icon: 'ShieldCheck',
    color: '#ef4444',
    config: { maxInputLength: 10000, blockInjections: true, sanitizeHtml: true, allowedSchemas: [] },
    tags: ['validation', 'input', 'sanitization', 'security'],
  },
  {
    id: 'guardrail-output-sanitizer',
    name: 'Output Sanitizer',
    category: 'guardrail',
    description: 'Sanitize agent outputs to remove or mask sensitive information such as API keys, passwords, personal data, and internal system details before returning to the user.',
    icon: 'ShieldAlert',
    color: '#ef4444',
    config: { maskSecrets: true, removePii: true, patterns: ['api_key', 'password', 'token', 'secret'], maskChar: '*' },
    tags: ['sanitization', 'output', 'pii', 'security'],
  },
  {
    id: 'guardrail-token-budget',
    name: 'Token Budget',
    category: 'guardrail',
    description: 'Enforce a maximum token budget per conversation, session, or time period. Prevents runaway costs by capping the total tokens consumed by model inference and tool calls.',
    icon: 'Coins',
    color: '#ef4444',
    config: { maxTokensPerRequest: 4096, maxTokensPerSession: 100000, maxTokensPerDay: 1000000, warningThreshold: 0.8 },
    tags: ['tokens', 'budget', 'cost-control'],
  },
  {
    id: 'guardrail-scope-limiter',
    name: 'Scope Limiter',
    category: 'guardrail',
    description: 'Restrict the agent to operate only within defined boundaries. Limits file system access to specific directories, blocks certain commands, and constrains network access.',
    icon: 'Fence',
    color: '#ef4444',
    config: { allowedPaths: ['/workspace'], blockedCommands: ['rm -rf', 'sudo', 'chmod 777'], allowNetwork: true, allowedDomains: [] },
    tags: ['scope', 'restrictions', 'sandboxing'],
  },
  {
    id: 'guardrail-human-in-the-loop',
    name: 'Human in the Loop',
    category: 'guardrail',
    description: 'Require human approval before executing high-impact actions such as deployments, database mutations, file deletions, or external API calls with side effects.',
    icon: 'UserCheck',
    color: '#ef4444',
    config: { requireApproval: ['deploy', 'delete', 'write-db', 'external-api'], timeout: 300, autoReject: true },
    tags: ['approval', 'human-review', 'safety'],
  },
  {
    id: 'guardrail-audit-logger',
    name: 'Audit Logger',
    category: 'guardrail',
    description: 'Log all agent actions, tool calls, and decisions for compliance and debugging. Records timestamps, inputs, outputs, and decision rationale in a tamper-evident format.',
    icon: 'ScrollText',
    color: '#ef4444',
    config: { logLevel: 'info', destination: 'file', format: 'json', retentionDays: 90, includeInputs: true, includeOutputs: true },
    tags: ['logging', 'audit', 'compliance', 'observability'],
  },
];
