import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  const body = await request.json();
  const { messages, agentConfig } = body;

  const systemPrompt = agentConfig?.systemPrompt || 'You are a helpful GitHub Copilot agent.';
  const agentName = agentConfig?.name || 'Copilot Agent';

  const tools = (agentConfig?.nodes || [])
    .filter((n: { type: string }) => n.type === 'tool')
    .map((n: { data: { label: string; description: string } }) => n.data.label);

  const lastMessage = messages[messages.length - 1]?.content || '';

  // Simulate agent response with tool calls
  const toolCallResults = [];
  if (lastMessage.toLowerCase().includes('file') || lastMessage.toLowerCase().includes('read')) {
    toolCallResults.push({
      id: crypto.randomUUID(),
      name: 'read_file',
      arguments: '{"path": "src/app/page.tsx"}',
      result: '// Next.js page component\nexport default function Page() {\n  return <div>Hello World</div>;\n}',
    });
  }
  if (lastMessage.toLowerCase().includes('terminal') || lastMessage.toLowerCase().includes('run') || lastMessage.toLowerCase().includes('command')) {
    toolCallResults.push({
      id: crypto.randomUUID(),
      name: 'execute_command',
      arguments: '{"command": "ls -la"}',
      result: 'total 32\ndrwxr-xr-x  8 user user 4096 Feb 14 12:00 .\n-rw-r--r--  1 user user  512 Feb 14 12:00 package.json\n-rw-r--r--  1 user user 1024 Feb 14 12:00 tsconfig.json\ndrwxr-xr-x  3 user user 4096 Feb 14 12:00 src',
    });
  }

  const availableTools = tools.length > 0
    ? `\n\nI have access to the following tools: ${tools.join(', ')}.`
    : '';

  const responses: Record<string, string> = {
    default: `I'm **${agentName}**, your GitHub Copilot agent. I'm configured with ${tools.length} tools and ready to help you with your development tasks.${availableTools}\n\nHow can I assist you today?`,
    help: `Here's what I can do:\n\n${tools.map((t: string) => `- **${t}**: Ready to use`).join('\n') || '- General assistance'}\n\nJust describe what you need and I'll use the appropriate tools.`,
    code: `Here's a code suggestion based on your request:\n\n\`\`\`typescript\n// Generated by ${agentName}\nexport function processData(input: string): string {\n  const parsed = JSON.parse(input);\n  return Object.keys(parsed)\n    .map(key => \`\${key}: \${parsed[key]}\`)\n    .join('\\n');\n}\n\`\`\`\n\nWould you like me to modify this or create additional functions?`,
  };

  let responseContent = responses.default;
  if (lastMessage.toLowerCase().includes('help')) {
    responseContent = responses.help;
  } else if (lastMessage.toLowerCase().includes('code') || lastMessage.toLowerCase().includes('function') || lastMessage.toLowerCase().includes('write')) {
    responseContent = responses.code;
  } else if (lastMessage.length > 10) {
    responseContent = `I've analyzed your request: "${lastMessage.substring(0, 100)}..."\n\n${toolCallResults.length > 0 ? 'I executed the following tools:\n\n' + toolCallResults.map(t => `**${t.name}**:\n\`\`\`\n${t.result}\n\`\`\``).join('\n\n') + '\n\n' : ''}Based on my analysis, here's my recommendation:\n\n1. The codebase structure looks well-organized\n2. Consider adding error handling for edge cases\n3. I can help implement any specific changes you need\n\nWhat would you like me to do next?`;
  }

  return NextResponse.json({
    message: {
      id: crypto.randomUUID(),
      role: 'assistant',
      content: responseContent,
      timestamp: new Date().toISOString(),
      toolCalls: toolCallResults.length > 0 ? toolCallResults : undefined,
    },
  });
}
